[config]
default_to_workspace = false
skip_core_tasks = true

[env]
TARGET_DIR = "${PWD}/res"

[tasks.default]
alias = "build"

[tasks.clippy]
dependencies = ["build-proxy-token"]
command = "cargo"
args = ["clippy", "--workspace", "--all-targets"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.build]
dependencies = ["build-factory", "rename-contract"]

[tasks.build-factory]
dependencies = ["build-proxy-token"]
command = "cargo"
args = [
    "near",
    "build",
    "non-reproducible-wasm",
    "--out-dir",
    "${TARGET_DIR}",
    "--manifest-path",
    "factory/Cargo.toml",
    "--no-embed-abi",
    "--no-abi",
]

[tasks.build-proxy-token]
command = "cargo"
args = [
    "near",
    "build",
    "non-reproducible-wasm",
    "--out-dir",
    "${TARGET_DIR}",
    "--manifest-path",
    "proxy-token/Cargo.toml",
    "--no-embed-abi",
    "--no-abi",
]

[tasks.rename-contract]
script = "mv ${TARGET_DIR}/aurora_proxy_factory.wasm ${TARGET_DIR}/aurora-proxy-factory.wasm"

[tasks.test]
alias = "tests"

[tasks.tests]
dependencies = ["build-proxy-token"]
run_task = "run-tests"

[tasks.run-tests]
command = "cargo"
args = ["test", "--workspace", "--all-targets", "${@}"]

[tasks.clean]
dependencies = ["rm-contracts"]
command = "cargo"
args = ["clean"]

[tasks.rm-contracts]
script = "rm -rf ${TARGET_DIR}/*proxy*.wasm"

[tasks.contract-stats]
category = "Tools"
script = "cd ${TARGET_DIR} && du -ah *.wasm"
