---
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

name: Build
jobs:
  build:
    name: Build contracts
    runs-on: k8s-infrastructure-generic
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libudev-dev build-essential pkg-config
      - name: Clone the repository
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install plugins
        run: cargo install cargo-make cargo-near
      - name: Compile contract
        run: cargo make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contracts
          path: res/aurora-proxy-factory.wasm

  publish:
    name: Publish contracts
    runs-on: k8s-infrastructure-generic
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Publish contracts for ${{ github.ref }} release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          file: contracts/aurora-proxy-factory.wasm
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
