name: Tests
on:
  pull_request:

jobs:
  formatting:
    name: Code Formatting
    runs-on: runs-on=${{ github.run_id }}/family=c5a.2xlarge+c6a.2xlarge/image=ubuntu24-full-x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libudev-dev build-essential pkg-config libssl-dev
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: cargo install cargo-make
      - run: cargo make fmt

  linter:
    name: Code Linter
    runs-on: runs-on=${{ github.run_id }}/family=c5a.2xlarge+c6a.2xlarge/image=ubuntu24-full-x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libudev-dev build-essential pkg-config libssl-dev
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: cargo install cargo-make
      - name: Run cargo clippy
        run: cargo make clippy

  tests:
    name: Tests
    runs-on: runs-on=${{ github.run_id }}/family=c5a.2xlarge+c6a.2xlarge/image=ubuntu24-full-x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libudev-dev build-essential pkg-config libssl-dev
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: cargo install cargo-make cargo-near
      - name: Run cargo test
        run: cargo make test
