name: Tests
on:
  pull_request:

jobs:
  formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: cargo install cargo-make cargo-near
      - run: cargo make fmt

  linter:
    name: Code Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: cargo install cargo-make cargo-near
      - name: Run cargo clippy
        run: cargo make clippy

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: cargo install cargo-make cargo-near
      - name: Run cargo test
        run: cargo make test
